# Generated by Django 4.0.5 on 2022-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount_percent',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GN', 'Gin'), ('RM', 'Rum'), ('TQ', 'Tequila'), ('VK', 'Vodka'), ('WS', 'Whiskey'), ('WN', 'Wine')], max_length=2),
        ),
    ]
